### ISSUE TITLE
No dialog with Sketch 3.2.2

### ISSUE THREAD

**Issue by rguldener** [Falkeyn/Modulizer#1]
Tried to use the plugin with Sketch 3.2.2 on OS X 10.10.2 but when I create a rectangle with some text inside, select both and press ⌘ + Shift + M the layers get grouped but no dialog box appears. If I manually edit the name of the rectangle layer and then press ⌘ + Shift + M the resizing works.

Would be an awesome plugin if you could fix that!

**Comment by jaznz** [comment]
Hi there. I was so happy to find this plugin! But the shortcut does not work for me either - Shift + ⌘ + M does not produce a paddings dialogue. Any ideas on why this is? Thanks

**Comment by plainclothes** [comment]
Still here in 3.4.4 ... haven't tried 3.5 yet.

**Comment by Falkeyn** [comment]
@plainclothes what's error shows in the logs?

**Comment by plainclothes** [comment]
Sorry, I didn't save the log. I only tried it briefly. When I hit this
error I switched to a more recently updated plug in.

## 

---

David Holman

## 541-621-2651

**Comment by Falkeyn** [comment]
@plainclothes It would be great if you can open Console, run Modulizer and copy the log message here. So I can figure out what's wrong
