### ISSUE TITLE
Not working in 3.4

### ISSUE THREAD

**Issue by jarisanders** [Falkeyn/Modulizer#3]
Error message:

Select one or more layers to convert them to the module with paddings. Select existing module for paddings update.

Try again

**Comment by Falkeyn** [comment]
Yes, I got it. But it's gone after reinstalling plugin.
Please try to remove and instal again

**Comment by Falkeyn** [comment]
It is Sketch bug. Sometimes context.selection property contain selection from another document. And context apparently too. In fact the plugin is running in another window :) 
https://www.facebook.com/groups/sketchformac/1632427083676110/?comment_id=1632544503664368&notif_t=like

**Comment by mikeprecious** [comment]
This may seem like a very redundant question: By "reinstalling" a plugin, it entails: 1) Removing the plugin [folder] from Sketch's plugins parent folder, and 2) Re-placing the plugin folder back in to the Sketch plugins parent folder - correct?

**Comment by Falkeyn** [comment]
Modulizer has no folder, it is one file «Modulizer.sketchplugin» only. 
To reinstall:
1. Remove this file from Sketch Plugins Folder
2. Download latest version https://github.com/Falkeyn/Modulizer/archive/master.zip and unzip
3. Simply double click on downloaded «Modulizer.sketchplugin» file (or put it to plugins folder manualy)

But It will not solve the problem. Sketch 3.4 have a bug and we should wait for 3.4.1 release
