### ISSUE TITLE
3.5 Update

### ISSUE THREAD

**Issue by sisomollov** [Falkeyn/Modulizer#5]
The plug-n stopped working after 3.5 update.

**Comment by sunnythaper** [comment]
For me as well.

**Comment by jordaniusrex** [comment]
+1

**Comment by Falkeyn** [comment]
resizeRoot for MSLayerGroup stopped working

**Comment by webchun** [comment]
+1 for me too

**Comment by Falkeyn** [comment]
Fixed

**Comment by webchun** [comment]
still doesnt work for me :(

**Comment by Falkeyn** [comment]
@webchun whats the error message in the log console?

**Comment by Falkeyn** [comment]
@webchun Sorry! I forgot to commit :) Please try again

**Comment by webchun** [comment]
umm have you pushed the changes yet? Latest commit on the main page https://github.com/Falkeyn/Modulizer still 4 months ago

**Comment by webchun** [comment]
ah ok, nice it works perfectly now ;) thanks!
