### ISSUE TITLE
3.5.2 Update

### ISSUE THREAD

**Issue by MDBas** [Falkeyn/Modulizer#6]
Plugin seems to have stopped working in 3.5.2.
This is what I get when applying padding:
![screen shot 2016-02-11 at 09 38 04](https://cloud.githubusercontent.com/assets/12843221/12972202/67bdd31a-d0a3-11e5-8ea5-03688e0ecfb1.png)

**Comment by Falkeyn** [comment]
I tried it and all works for me on 3.5.2
Please update to the latest version and try again

**Comment by MDBas** [comment]
You're right. I thought [Sketch Toolbox](http://sketchtoolbox.com/) automatically kept it up to date, but apparently not.
After uninstalling and reinstalling it works.
Thanks for looking into it!
